import { parseProgression } from "./chords";
import { DEFAULT_PARAMS, steps } from "./params";
import { autoLoops } from "./playback";
import type { Song, SongParams } from "./types";

/**
 * The songs that ship with the app. The first four are pinned on a fresh install, so they cover the
 * main moods: rain, jazz, wind, tape. Every song starts from the same defaults and overrides what
 * gives it its character; they are spread over voices, kits, tempos and lengths so that no two
 * sound alike (a test checks it).
 */
const { volume: _volume, ...base } = DEFAULT_PARAMS;

type Row = "kick" | "snare" | "hat" | "bass" | "keys" | "lead";

interface Definition {
  id: string;
  name: string;
  description: string;
  bpm: number;
  swing: number;
  /** Chord symbols, one per bar: `"Dm9 G13 Cmaj7 A7"`. */
  chords: string;
  /** 16 steps per track, `x` = hit. A missing row is silent. */
  pattern: Partial<Record<Row, string>>;
  ambience: SongParams["ambience"];
  fx: SongParams["fx"];
  keys?: Partial<SongParams["keys"]>;
  bass?: Partial<SongParams["bass"]>;
  drums?: Partial<SongParams["drums"]>;
  pad?: Partial<SongParams["pad"]>;
  lead?: Partial<SongParams["lead"]>;
  humanize?: number;
}

const REST = "................";

function build(d: Definition): Song {
  const row = (name: Row) => steps(d.pattern[name] ?? REST);
  const progression = parseProgression(d.chords);
  return {
    id: d.id,
    name: d.name,
    description: d.description,
    createdAt: 0,
    builtIn: true,
    params: {
      ...base,
      bpm: d.bpm,
      swing: d.swing,
      humanize: d.humanize ?? base.humanize,
      loops: autoLoops({ bpm: d.bpm, progression }),
      progression,
      pattern: { kick: row("kick"), snare: row("snare"), hat: row("hat"), bass: row("bass"), keys: row("keys"), lead: row("lead") },
      keys: { ...base.keys, ...d.keys },
      bass: { ...base.bass, ...d.bass },
      drums: { ...base.drums, ...d.drums },
      pad: { ...base.pad, ...d.pad },
      lead: { ...base.lead, ...d.lead },
      ambience: d.ambience,
      fx: d.fx,
    },
  };
}

const definitions: Definition[] = [
  {
    id: "rainy-study",
    name: "Rainy Study",
    description: "Electric piano, steady rain, warm vinyl.",
    bpm: 74,
    swing: 0.5,
    chords: "Dm9 G13 Cmaj7 A7",
    pattern: { kick: "x......x..x.....", snare: "....x.......x...", hat: "x.x.x.x.x.x.x.x.", bass: "x..x..x...x.....", keys: "x......x..x....." },
    ambience: { rain: 0.55, vinyl: 0.3, wind: 0 },
    fx: { tone: 4600, wobble: 0.3, warmth: 0.3, reverb: 0.28 },
  },
  {
    id: "midnight-jazz",
    name: "Midnight Jazz",
    description: "Felt piano, upright bass and brushes, eight bars of ii-V-I.",
    bpm: 88,
    swing: 0.68,
    chords: "Cmaj7 Am9 Dm9 G13 Em7 A7 Dm9 G13",
    pattern: { kick: "x.........x.....", snare: "....x.......x..x", hat: "x..xx..xx..xx..x", bass: "x...x...x...x...", keys: "x....x.....x...." },
    ambience: { rain: 0, vinyl: 0.5, wind: 0 },
    fx: { tone: 6200, wobble: 0.15, warmth: 0.35, reverb: 0.3 },
    keys: { voice: "piano", level: 0.6, adsr: { attack: 0.005, decay: 1.4, sustain: 0.1, release: 1 }, cutoff: 4200, lfoDepth: 0.1 },
    bass: { voice: "upright", level: 0.8, cutoff: 700 },
    drums: { kit: "brushes", kick: 0.6, snare: 0.6, hat: 0.7 },
  },
  {
    id: "sunday-wind",
    name: "Sunday Wind",
    description: "Nylon guitar, a soft flute and drifting wind.",
    bpm: 66,
    swing: 0.3,
    chords: "Am9 Fmaj7 Cmaj7 E7",
    pattern: {
      kick: "x.......x.......",
      snare: "........x.......",
      hat: "x...x...x...x...",
      bass: "x.......x.....x.",
      keys: "x..x..x.x..x..x.",
      lead: "x.....x.....x...",
    },
    ambience: { rain: 0, vinyl: 0.15, wind: 0.6 },
    fx: { tone: 6000, wobble: 0.15, warmth: 0.2, reverb: 0.42 },
    keys: { voice: "guitar", level: 0.65, adsr: { attack: 0.01, decay: 2, sustain: 0.2, release: 1 }, cutoff: 4000, lfoDepth: 0.1 },
    bass: { voice: "upright", level: 0.6 },
    drums: { kit: "brushes", kick: 0.55, snare: 0.4, hat: 0.4 },
    pad: { level: 0.3, voice: "air", attack: 2 },
    lead: { level: 0.4, voice: "flute", echo: 0.35 },
  },
  {
    id: "tape-cafe",
    name: "Tape Café",
    description: "Worn tape, wobbly keys, rubbery bass and a little square hook.",
    bpm: 90,
    swing: 0.58,
    chords: "Ebmaj7 Cm9 Fm9 Bb13",
    pattern: {
      kick: "x.....x..x.....x",
      snare: "....x.......x...",
      hat: "x.x.x.xxx.x.x.xx",
      bass: "x..x..x...x..x..",
      keys: "x..x....x..x....",
      lead: "..........x.x...",
    },
    ambience: { rain: 0.1, vinyl: 0.6, wind: 0 },
    fx: { tone: 3800, wobble: 0.7, warmth: 0.6, reverb: 0.18 },
    keys: { wave: "triangle", lfoRate: 0.6, lfoDepth: 0.55, cutoff: 2400 },
    bass: { voice: "synth", wave: "square", cutoff: 380 },
    drums: { kick: 1, snare: 0.8, hat: 0.7 },
    lead: { level: 0.25, voice: "square", echo: 0.45 },
  },
  {
    id: "slow-sunrise",
    name: "Slow Sunrise",
    description: "Barely a beat: piano, a swelling pad and a flute.",
    bpm: 62,
    swing: 0.5,
    chords: "Fmaj7 Em7 Dm9 G13",
    pattern: { kick: "x.........x.....", hat: "x.......x.......", bass: "x...............", keys: "x.......x.......", lead: "..x.....x...x..." },
    ambience: { rain: 0, vinyl: 0.15, wind: 0.25 },
    fx: { tone: 7500, wobble: 0.1, warmth: 0.15, reverb: 0.5 },
    keys: { voice: "piano", level: 0.5, cutoff: 5000, lfoDepth: 0.1 },
    bass: { voice: "upright", level: 0.55 },
    drums: { kick: 0.5, snare: 0, hat: 0.35 },
    pad: { level: 0.5, voice: "warm", attack: 2.5, cutoff: 2400 },
    lead: { level: 0.35, voice: "flute", echo: 0.4 },
  },
  {
    id: "neon-rain",
    name: "Neon Rain",
    description: "Synth bass, deep kit, a square lead echoing down wet streets.",
    bpm: 84,
    swing: 0.3,
    chords: "Gm9 C13 Fmaj7 Bbmaj7",
    pattern: {
      kick: "x.....x..x......",
      snare: "....x.......x...",
      hat: "xxxxxxxxxxxxxxxx",
      bass: "x..x....x.x..x..",
      keys: "x...............",
      lead: "x..x..x...x.x...",
    },
    ambience: { rain: 0.7, vinyl: 0.1, wind: 0 },
    fx: { tone: 5200, wobble: 0.25, warmth: 0.4, reverb: 0.4 },
    keys: { wave: "sawtooth", cutoff: 1800, lfoRate: 2.5, lfoDepth: 0.6, level: 0.4 },
    bass: { voice: "synth", wave: "sawtooth", cutoff: 500 },
    drums: { kit: "deep", hat: 0.3 },
    pad: { level: 0.3, voice: "strings", attack: 1, cutoff: 1500 },
    lead: { level: 0.35, voice: "square", echo: 0.55 },
  },
  {
    id: "library-hush",
    name: "Library Hush",
    description: "Quiet piano over a faint pad, loose timing, room to think.",
    bpm: 64,
    swing: 0.4,
    chords: "Em9 A13 Dmaj7 Bm7",
    pattern: { kick: "x...............", snare: "........x.......", hat: "..x...x...x...x.", bass: "x.......x.......", keys: "x.....x.....x..." },
    ambience: { rain: 0, vinyl: 0.5, wind: 0.05 },
    fx: { tone: 4000, wobble: 0.2, warmth: 0.3, reverb: 0.45 },
    keys: { voice: "piano", level: 0.45, cutoff: 2600, lfoDepth: 0.2 },
    bass: { level: 0.5, cutoff: 300 },
    drums: { kit: "brushes", kick: 0.4, snare: 0.35, hat: 0.35 },
    pad: { level: 0.25, voice: "warm", attack: 2, cutoff: 1200 },
    humanize: 0.6,
  },
  {
    id: "train-window",
    name: "Train Window",
    description: "Strummed guitar over a steady four-on-the-floor.",
    bpm: 92,
    swing: 0.25,
    chords: "Bbmaj7 Gm9 Cm9 F13",
    pattern: { kick: "x...x...x...x...", snare: "....x.......x...", hat: "..x...x...x...x.", bass: "x.....x.x.....x.", keys: "x.x...x.x.x...x." },
    ambience: { rain: 0.25, vinyl: 0.1, wind: 0.35 },
    fx: { tone: 5600, wobble: 0.2, warmth: 0.3, reverb: 0.25 },
    keys: { voice: "guitar", level: 0.6, cutoff: 3600, lfoDepth: 0.1 },
    drums: { kick: 0.75 },
    pad: { level: 0.25, voice: "warm", attack: 1.5 },
  },
  {
    id: "late-bus-home",
    name: "Late Bus Home",
    description: "Two chords, heavy crackle and a music box half asleep.",
    bpm: 72,
    swing: 0.62,
    chords: "Am9 D13",
    pattern: {
      kick: "x.......x.x.....",
      snare: "........x.......",
      hat: "x...x...x...x.x.",
      bass: "x.....x..x......",
      keys: "x.....x......x..",
      lead: "x.......x....x..",
    },
    ambience: { rain: 0, vinyl: 0.8, wind: 0.1 },
    fx: { tone: 3400, wobble: 0.45, warmth: 0.5, reverb: 0.3 },
    keys: { lfoRate: 0.35, lfoDepth: 0.4, cutoff: 2300 },
    bass: { voice: "upright" },
    drums: { kit: "deep", kick: 0.7, snare: 0.6 },
    lead: { level: 0.3, voice: "musicbox", echo: 0.6 },
  },
  {
    id: "cozy-blanket",
    name: "Cozy Blanket",
    description: "Muffled organ and a warm pad while it pours outside.",
    bpm: 68,
    swing: 0.35,
    chords: "Cmaj7 Fmaj7 Em7 A7",
    pattern: { kick: "x.......x..x....", snare: "....x.......x...", hat: "x.x...x.x.x...x.", bass: "x.......x.......", keys: "x.......x......." },
    ambience: { rain: 0.45, vinyl: 0.3, wind: 0 },
    fx: { tone: 2800, wobble: 0.35, warmth: 0.7, reverb: 0.35 },
    keys: { voice: "organ", level: 0.45, cutoff: 1500, lfoDepth: 0.3, adsr: { attack: 0.08, decay: 1, sustain: 0.8, release: 1.2 } },
    drums: { kit: "brushes" },
    pad: { level: 0.45, voice: "warm", attack: 1.8, cutoff: 1400 },
  },
  {
    id: "vinyl-sunday",
    name: "Vinyl Sunday",
    description: "A dusty record: piano, round bass, a lazy flute.",
    bpm: 80,
    swing: 0.64,
    chords: "Dm9 Bbmaj7 Fmaj7 C13",
    pattern: {
      kick: "x..x......x.....",
      snare: "....x.......x...",
      hat: "x.x.x.x.x.x.x.x.",
      bass: "x..x......x.....",
      keys: "x.....x.....x...",
      lead: "......x.x.....x.",
    },
    ambience: { rain: 0, vinyl: 0.9, wind: 0 },
    fx: { tone: 4200, wobble: 0.5, warmth: 0.45, reverb: 0.2 },
    keys: { voice: "piano", cutoff: 3000 },
    lead: { level: 0.3, voice: "flute", echo: 0.2 },
  },
  {
    id: "deep-focus",
    name: "Deep Focus",
    description: "Half-time 808 pulse, low sub and strings to lock in.",
    bpm: 76,
    swing: 0.45,
    chords: "Cm9 F13 Bbmaj7 Ebmaj7",
    pattern: { kick: "x.......x.x.....", snare: "........x.......", hat: "x.x.x.x.x.x.x.x.", bass: "x.......x.x.....", keys: "x.......x......." },
    ambience: { rain: 0.1, vinyl: 0.25, wind: 0 },
    fx: { tone: 4600, wobble: 0.15, warmth: 0.35, reverb: 0.25 },
    keys: { level: 0.45, cutoff: 2400, lfoDepth: 0.25 },
    bass: { cutoff: 260, level: 0.8 },
    drums: { kit: "deep", kick: 1, snare: 0.6, hat: 0.45 },
    pad: { level: 0.3, voice: "strings", attack: 1.2, cutoff: 1300 },
  },
  {
    id: "low-tide",
    name: "Low Tide",
    description: "Vibraphone and two chords rolling in like waves.",
    bpm: 70,
    swing: 0.45,
    chords: "Ebmaj7 Abmaj7",
    pattern: {
      kick: "x.........x.....",
      snare: "....x.......x...",
      hat: "x.x.x.x.x.x.x.x.",
      bass: "x.........x.....",
      keys: "x..x......x.....",
      lead: "....x.......x..x",
    },
    ambience: { rain: 0, vinyl: 0.1, wind: 0.45 },
    fx: { tone: 5500, wobble: 0.3, warmth: 0.2, reverb: 0.6 },
    keys: { voice: "vibes", level: 0.5, cutoff: 3800, lfoRate: 0.2, lfoDepth: 0.2 },
    bass: { voice: "synth", wave: "sine", cutoff: 320 },
    drums: { kit: "brushes", kick: 0.6, snare: 0.4, hat: 0.4 },
    pad: { level: 0.4, voice: "air", attack: 2.5 },
    lead: { level: 0.3, voice: "flute", echo: 0.6 },
  },
  {
    id: "snow-globe",
    name: "Snow Globe",
    description: "No drums, just a music box turning in the cold.",
    bpm: 60,
    swing: 0.2,
    chords: "Fmaj7 Am9 Bbmaj7 C13",
    pattern: { hat: "x...x...x...x...", bass: "x.......x.......", keys: "x...............", lead: "x.x.x...x.x.x..." },
    ambience: { rain: 0, vinyl: 0.2, wind: 0.35 },
    fx: { tone: 8000, wobble: 0.1, warmth: 0.1, reverb: 0.55 },
    keys: { voice: "piano", level: 0.35, cutoff: 4500 },
    bass: { level: 0.4 },
    drums: { kick: 0, snare: 0, hat: 0.2 },
    pad: { level: 0.45, voice: "air", attack: 3 },
    lead: { level: 0.5, voice: "musicbox", echo: 0.4 },
  },
  {
    id: "arcade-nights",
    name: "Arcade Nights",
    description: "Fast and bright: organ stabs, saw bass, a square-wave hook.",
    bpm: 96,
    swing: 0.2,
    chords: "Am9 Fmaj7 G13 Em7",
    pattern: {
      kick: "x.....x.x.......",
      snare: "....x.......x...",
      hat: "x.xxx.xxx.xxx.xx",
      bass: "x.x...x.x.x...x.",
      keys: "..x...x...x...x.",
      lead: "x.x.x..xx.x.x...",
    },
    ambience: { rain: 0, vinyl: 0.2, wind: 0 },
    fx: { tone: 9000, wobble: 0.1, warmth: 0.4, reverb: 0.2 },
    keys: { voice: "organ", level: 0.4, cutoff: 3200, lfoDepth: 0.15, adsr: { attack: 0.005, decay: 0.3, sustain: 0.8, release: 0.2 } },
    bass: { voice: "synth", wave: "sawtooth", cutoff: 600 },
    drums: { kit: "deep", hat: 0.45 },
    lead: { level: 0.4, voice: "square", echo: 0.3 },
  },
  {
    id: "paper-lanterns",
    name: "Paper Lanterns",
    description: "Electric piano and flute over open chords, light rain on paper.",
    bpm: 78,
    swing: 0.55,
    chords: "Dm11 Gm11 Dm11 Am9",
    pattern: {
      kick: "x.....x...x.....",
      snare: "....x.......x...",
      hat: "x.x.x.x.x.x.x.x.",
      bass: "x.....x...x.....",
      keys: "x.x.....x.x.....",
      lead: "x..x.x......x.x.",
    },
    ambience: { rain: 0.4, vinyl: 0.1, wind: 0.1 },
    fx: { tone: 5000, wobble: 0.2, warmth: 0.25, reverb: 0.35 },
    keys: { level: 0.5, cutoff: 3000, lfoDepth: 0.2 },
    bass: { voice: "upright", level: 0.6 },
    drums: { kit: "brushes" },
    lead: { level: 0.45, voice: "flute", echo: 0.3 },
  },
  {
    id: "rooftop-garden",
    name: "Rooftop Garden",
    description: "Bright electric piano and a music box on a sunny afternoon.",
    bpm: 86,
    swing: 0.5,
    chords: "Gmaj7 F#m7 Em9 A13",
    pattern: {
      kick: "x......x..x.....",
      snare: "....x.......x...",
      hat: "x.x.x.x.x.x.x.x.",
      bass: "x..x..x...x.....",
      keys: "x..x.....x......",
      lead: "......x.......x.",
    },
    ambience: { rain: 0, vinyl: 0.2, wind: 0.25 },
    fx: { tone: 8500, wobble: 0.15, warmth: 0.2, reverb: 0.25 },
    keys: { wave: "triangle", cutoff: 5000, lfoDepth: 0.2 },
    pad: { level: 0.25, voice: "warm", attack: 1 },
    lead: { level: 0.3, voice: "musicbox", echo: 0.3 },
  },
  {
    id: "night-shift",
    name: "Night Shift",
    description: "Three minor chords, organ and a heavy 808 in the rain.",
    bpm: 82,
    swing: 0.45,
    chords: "Bm9 Em9 F#7",
    pattern: { kick: "x.......x..x....", snare: "....x.......x...", hat: "x.x.x.x.x.x.x.x.", bass: "x.......x..x....", keys: "x.......x......." },
    ambience: { rain: 0.45, vinyl: 0.15, wind: 0 },
    fx: { tone: 3600, wobble: 0.3, warmth: 0.5, reverb: 0.3 },
    keys: { voice: "organ", level: 0.4, cutoff: 1800, lfoRate: 1, lfoDepth: 0.4 },
    bass: { voice: "synth", wave: "square", cutoff: 350 },
    drums: { kit: "deep", kick: 1, hat: 0.4 },
  },
  {
    id: "autumn-letters",
    name: "Autumn Letters",
    description: "Eight falling chords, fingerpicked guitar and slow strings.",
    bpm: 70,
    swing: 0.3,
    chords: "Am9 Dm9 G13 Cmaj7 Fmaj7 Bm7 E7 Am9",
    pattern: { kick: "x.......x.......", snare: "....x.......x...", hat: "x...x...x...x...", bass: "x.......x.......", keys: "x..x..x.x..x..x." },
    ambience: { rain: 0.1, vinyl: 0.45, wind: 0.2 },
    fx: { tone: 4400, wobble: 0.25, warmth: 0.35, reverb: 0.4 },
    keys: { voice: "guitar", level: 0.6, adsr: { attack: 0.01, decay: 2.4, sustain: 0.2, release: 1 } },
    bass: { voice: "upright" },
    drums: { kit: "brushes", kick: 0.6, snare: 0.5 },
    pad: { level: 0.4, voice: "strings", attack: 2, cutoff: 1600 },
  },
  {
    id: "coffee-steam",
    name: "Coffee Steam",
    description: "Heavy shuffle, vibraphone and upright bass in a rainy café.",
    bpm: 90,
    swing: 0.75,
    chords: "Fmaj7 Dm9 Gm9 C13",
    pattern: { kick: "x.x.......x..x..", snare: "....x.......x...", hat: "xxx.xxx.xxx.xxx.", bass: "x.x.......x..x..", keys: "x.....x..x......" },
    ambience: { rain: 0.35, vinyl: 0.3, wind: 0 },
    fx: { tone: 4800, wobble: 0.3, warmth: 0.55, reverb: 0.15 },
    keys: { voice: "vibes", level: 0.5, cutoff: 3200, lfoDepth: 0.2 },
    bass: { voice: "upright", level: 0.75 },
    drums: { kick: 1, snare: 0.9, hat: 0.6 },
    pad: { level: 0.3, voice: "warm", attack: 0.8, cutoff: 1500 },
  },
  {
    id: "stargazing",
    name: "Stargazing",
    description: "Vibraphone, a vast pad and a slow, deep kick in the dark.",
    bpm: 64,
    swing: 0.3,
    chords: "Dbmaj7 Bbm9 Ebm9 Ab13",
    pattern: { kick: "x.........x.....", hat: "....x.......x...", bass: "x.........x.....", keys: "x.......x......." },
    ambience: { rain: 0, vinyl: 0.1, wind: 0.2 },
    fx: { tone: 5000, wobble: 0.2, warmth: 0.2, reverb: 0.65 },
    keys: { voice: "vibes", level: 0.45, cutoff: 3000 },
    drums: { kit: "deep", kick: 0.6, snare: 0, hat: 0.3 },
    pad: { level: 0.5, voice: "air", attack: 3.5 },
  },
  {
    id: "subway-echoes",
    name: "Subway Echoes",
    description: "Shuffled drums, saw bass and a music box bouncing off the tiles.",
    bpm: 94,
    swing: 0.62,
    chords: "Cm9 Cm9 Abmaj7 G7",
    pattern: {
      kick: "x......xx.x.....",
      snare: "....x.......x...",
      hat: "x.x.x.x.x.x.x.x.",
      bass: "x.xx..x.x.xx..x.",
      keys: "x...............",
      lead: "x.....x...x.....",
    },
    ambience: { rain: 0.3, vinyl: 0, wind: 0.1 },
    fx: { tone: 6000, wobble: 0.2, warmth: 0.45, reverb: 0.35 },
    keys: { wave: "sawtooth", level: 0.35, cutoff: 1800, lfoDepth: 0.4 },
    bass: { voice: "synth", wave: "sawtooth", cutoff: 550, level: 0.75 },
    drums: { kick: 0.95 },
    lead: { level: 0.35, voice: "musicbox", echo: 0.7 },
  },
  {
    id: "green-tea",
    name: "Green Tea",
    description: "Picked guitar and flute, calm and unhurried.",
    bpm: 74,
    swing: 0.35,
    chords: "Ebmaj7 Fm9 Gm9 Abmaj7",
    pattern: {
      kick: "x.......x.......",
      snare: "....x.......x...",
      hat: "x.x.x.x.x.x.x.x.",
      bass: "x.......x.......",
      keys: "x.x.x.x.x.x.x.x.",
      lead: "x.......x...x...",
    },
    ambience: { rain: 0.1, vinyl: 0.3, wind: 0.15 },
    fx: { tone: 6500, wobble: 0.1, warmth: 0.2, reverb: 0.3 },
    keys: { voice: "guitar", level: 0.5, cutoff: 4500, adsr: { attack: 0.01, decay: 1, sustain: 0.1, release: 0.6 } },
    bass: { voice: "synth", wave: "sine", cutoff: 300 },
    drums: { kick: 0.6, snare: 0.45, hat: 0.35 },
    lead: { level: 0.4, voice: "flute", echo: 0.25 },
  },
  {
    id: "moonlit-pier",
    name: "Moonlit Pier",
    description: "Piano and strings, no drums but a whisper of hi-hat.",
    bpm: 68,
    swing: 0.3,
    chords: "Em9 Cmaj7 Am9 B7",
    pattern: { hat: "..x...x...x...x.", bass: "x.......x.......", keys: "x.......x..x...." },
    ambience: { rain: 0, vinyl: 0.2, wind: 0.35 },
    fx: { tone: 5200, wobble: 0.2, warmth: 0.25, reverb: 0.55 },
    keys: { voice: "piano", level: 0.55, cutoff: 3500 },
    bass: { voice: "upright", level: 0.55 },
    drums: { kick: 0, snare: 0, hat: 0.3 },
    pad: { level: 0.4, voice: "strings", attack: 2.5, cutoff: 1400 },
  },
];

/** Ships with the app; never saved to the config file. */
export const BUILT_IN_SONGS: Song[] = definitions.map(build);
